Iter5
agatma/metrics pull request #5
Opened 2024-05-01 16:31 UTC by agatma

2024-05-04 16:14 UTC, s-shpak requested changes
Добавь, пожалуйста, в проект линтер (см. https://github.com/s-shpak/praktikum-golangci-lint) и поправь проблемы, которые он найдет

2024-05-04 16:14 UTC, s-shpak commented on cmd/agent/flags.go
> +var flagRunAddr *string
Глобальные переменные не нужны, инициализируй их внутри `NewConfig`

2024-05-04 16:14 UTC, s-shpak commented on cmd/agent/flags.go
> +func init() {
`init` не нужен, парси флаги внутри функции `GetConfig`, которая будет вызываться из `main`

2024-05-04 16:14 UTC, s-shpak commented on cmd/agent/flags.go
> +	flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ExitOnError)
Вместо этого лучше просто использовать `flag.Parse`

2024-05-04 16:14 UTC, s-shpak commented on cmd/agent/flags.go
> +		log.Fatal(err)
См. видео и исправь это, пожалуйста: https://app.pachca.com/chats/9180496?message=234290731

2024-05-04 16:14 UTC, s-shpak commented on cmd/agent/flags.go
> +	"github.com/caarlos0/env/v6"
Существует 11 версия

2024-05-04 16:14 UTC, s-shpak commented on cmd/server/flags.go
Аналогичну агенту. Кстати, лучше назвать файл `config.go`, т.к. ты работаешь не только с флагами для получения конфигурации

2024-05-04 16:14 UTC, s-shpak commented on cmd/server/main.go
> +	fmt.Println("Running server on", cfg.Address)
Не используй `fmt`, лучше используй `log`

2024-05-04 16:14 UTC, s-shpak commented on cmd/server/main.go
> +	r := chi.NewRouter()
Очень много кода в `main`, лучше спрятать в `internal`

2024-05-04 16:14 UTC, s-shpak commented on internal/agent/run.go
> +	port := strings.Split(cfg.Address, ":")[1]
Здесь код может выбросить панику

2024-05-04 16:14 UTC, s-shpak commented on internal/agent/run.go
> +				log.Fatal(err)
См. видео про ошибки

2024-05-04 16:14 UTC, s-shpak commented on internal/agent/storage/metricStorage.go
> +	Mutex   sync.RWMutex
1. Хорошей практикой будет сделать этот мьютекс указателем
2. Мьютекс никогда нельзя экспортировать, им должен управлять сам объект

2024-05-04 16:14 UTC, s-shpak commented on internal/server/handlers/handlers.go
> +func handleError(res http.ResponseWriter, errMsg string, statusCode int) {
Кажется, что эта обертка не нужна

2024-05-04 16:14 UTC, s-shpak commented on internal/server/storage/storage.go
> +	mutex         sync.RWMutex
Не стоит использовать `RWMutex`: скорее всего твой код будет работать медленее, чем с обычным мьютексом

2024-05-04 16:14 UTC, s-shpak commented on internal/server/storage/storage.go
> +type MetricRepository interface {
Зачем этот интерфейс ?

2024-05-05 12:36 UTC, agatma commented on internal/server/storage/storage.go
> +type MetricRepository interface {
Сделал рефакторинг проекта

2024-05-05 12:41 UTC, agatma commented on cmd/agent/flags.go
> +		log.Fatal(err)
Видео не грузит. В следующем спринте исправлю

2024-05-05 12:41 UTC, agatma commented on internal/agent/run.go
> +				log.Fatal(err)
Видео не грузит. В следующем спринте исправлю

2024-05-06 12:43 UTC, s-shpak commented on internal/agent/adapters/workers/config.go
> +		log.Fatal(err)
Фаталиться из глубины кода нельзя

2024-05-06 12:48 UTC, s-shpak commented on cmd/agent/main.go
> +		return fmt.Errorf("failed to initialize a storage: %w", err)
В сообщении ошибки лучше отметить, какой `storage` инициализирован

2024-05-06 12:49 UTC, s-shpak commented on internal/agent/core/service/service.go
> +var errTypeNotFound = errors.New("metric type is not found")
Зачем объявлять эту ошибку, если она не экспортируется

2024-05-06 12:55 UTC, s-shpak commented on internal/agent/core/service/service.go
> +	response = a.counterAgentStorage.SetMetricValue(&domain.SetMetricRequest{
Здесь неверная логика управлением метрики. Сервер должен хранить значение равное количеству сбора метрик на агенте. Подумай, как правильно это сделать (или почитай треды в пачке, там это обсуждалось)

2024-05-06 13:02 UTC, s-shpak commented on internal/server/core/validation/validate.go
> +	_, err := strconv.Atoi(value)
Ты вызываешь этот метод здесь, а потом в `setCounterMetricValue`. Лучше сделать это только один раз

2024-05-06 13:03 UTC, s-shpak requested changes
См. комментарии.

Добавь меня в контрибьютеры, чтобы я мог резолвить комменты. Сам не резолвь их, пожалуйста, - мне надо видеть, что я просил изменить

2024-05-06 14:05 UTC, agatma commented
> См. комментарии.
> 
> Добавь меня в контрибьютеры, чтобы я мог резолвить комменты. Сам не резолвь их, пожалуйста, - мне надо видеть, что я просил изменить

2024-05-10 15:02 UTC, s-shpak commented on internal/agent/adapters/workers/worker.go
> +			pollCount++
Почему увеличение `PollCount` происходит после записи в хранилище ?

2024-05-10 16:33 UTC, agatma commented on internal/agent/adapters/workers/worker.go
> +			pollCount++
Обновил

2024-05-11 13:18 UTC, s-shpak approved these changes

2024-05-11 16:24 UTC, merged