Iter9
agatma/metrics pull request #9
Opened 2024-05-31 13:13 UTC by agatma

2024-06-02 19:51 UTC, s-shpak requested changes

2024-06-02 19:51 UTC, s-shpak commented on .golangci.yml
> +  # Default: use Go version from the go.mod files, fallback on the env var `GOVERSION`, fallback on 1.18
Откуда это изменение ? Если его автоматически делает какая-то утилита, то настрой ее так, чтобы она не проверяла этот файл

2024-06-02 19:51 UTC, s-shpak commented on cmd/agent/main.go
> +		log.Println(err)
Зачем это, если следующий вызов логирует ошибку ?

2024-06-02 19:51 UTC, s-shpak commented on internal/agent/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Глобальные переменные не нужны. Возвращай логгер при его инициализации и передавай туда, где он используется

2024-06-02 19:51 UTC, s-shpak commented on cmd/server/main.go
> +			logger.Log.Info("metrics are saved to file")
После выполнения этого вызова выполнение перейдет на строку 51, и приложение завершится с ошибкой

2024-06-02 19:51 UTC, s-shpak commented on cmd/server/main.go
> +	if cfg.StoreInterval == 0 {
Это неправильная логика. Вот правильная:

![ya-pr](https://github.com/agatma/metrics/assets/131411290/bb274725-6859-4c11-8a6b-8f9e3509a9e5)

2024-06-02 19:51 UTC, s-shpak commented on internal/agent/adapters/storage/memory/config.go
> +}
Зачем это изменение ?

2024-06-02 19:51 UTC, s-shpak commented on internal/server/adapters/api/middleware/middleware.go
> +			zap.Int("status", respData.status),
Какой статус будет залогирован, если `WriteHeader` не вызван ?

2024-06-02 19:51 UTC, s-shpak commented on internal/server/adapters/api/middleware/middleware.go
> +				w.WriteHeader(http.StatusInternalServerError)
Ошибки типа `InternalServerError` должны логироваться на стороне сервера

2024-06-02 19:51 UTC, s-shpak commented on internal/server/adapters/api/rest/rest_test.go
> +	metricStorage, _ := storage.NewStorage(storage.Config{
Ошибки надо проверять и в тестах

2024-06-02 19:51 UTC, s-shpak commented on internal/server/adapters/storage/file/storage.go
> +func NewStorage(cfg *Config) (*MetricStorage, error) {
1. Я бы организовал это по-другому:

я бы встроил in-memory store в файловое хранилище. Я загружал бы данные в память один раз: при инициализации хранилища. После чего я бы читал данные только из памяти. Запись зависила бы от режима работы (синхронный-асинхронный): в первом случае данные записываются сразу в память и в файл. Во втором случае сначала в память, потом асинххронно в файл

2. Асинхронная запись пока реализована неправильно: при ней записи должны сохраняться периодически, не при каждой записи новой порции метрик

2024-06-02 19:51 UTC, s-shpak commented on internal/server/adapters/storage/storage.go
> +	"github.com/agatma/sprint1-http-server/internal/server/adapters/storage/file"
Пора переименовать пакет:

```suggestion
	"github.com/agatma/metrics/internal/server/adapters/storage/file"
```

2024-06-02 19:51 UTC, s-shpak commented on internal/server/core/files/file.go
> +	if err = gob.NewDecoder(bytes.NewReader(data)).Decode(&metricValues); err != nil {
Не стоит, `gob` предназначен для другого. Используй просто `json`

2024-06-02 19:51 UTC, s-shpak commented on internal/server/core/service/service.go
> +		time.AfterFunc(timeDuration, func() {
Это выполнится одни раз. Смотри здесь, как это правильно реализовать: https://app.pachca.com/chats?thread_id=3778641&sidebar_message=252250473

2024-06-02 19:51 UTC, s-shpak commented on internal/shared-kernel/compress/gzip.go
> +func (c *Writer) Header() http.Header {
Используй встраивание (embedding), чтобы избежать таких ненужных объявлений

2024-06-05 08:25 UTC, agatma commented on internal/agent/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Это нужно будет толкать в каждую функцию. Как по мне -> антипаттерн. На работе так делаю. Оставим с глобальной инициализацией

2024-06-05 18:41 UTC, s-shpak commented on internal/agent/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Это не является анти-паттерном, скорее глобальный логгер является довольно плохим анти-паттерном, но если хочешь оставить, то я не против. Если захочешь, то можем обсудить на 1-1

2024-06-05 19:00 UTC, s-shpak requested changes

2024-06-05 19:00 UTC, s-shpak commented on internal/server/adapters/api/rest/rest_test.go
> +		t.Error(err)
Этот вызов не завершает тест. После него надо явно выходить из функции

2024-06-05 19:00 UTC, s-shpak commented on internal/server/adapters/storage/file/storage.go
>  type MetricStorage struct {
Все еще не нравится: создай две разные структуры `InMemoryStore` и `FileStore` (это лучше согласено принципу Separation of Concerns). Пусть первое встраивается во второе. Тогда первая структура будет реализовывать сохранение в память, а вторая - использовать этот функционал + сохранять записи в файл

2024-06-07 18:00 UTC, s-shpak approved these changes

2024-06-08 07:04 UTC, merged